# Use an official Python runtime as a parent image
FROM openeuler/openeuler:latest

WORKDIR /cache-proxy

# Add the current directory contents into the container at /cache-proxy
ADD . /cache-proxy
RUN yum install -y python3 python3-pip
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN mkdir /tmp/.cache

# Install any needed packages specified in requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run main.py when the container launches
ENTRYPOINT python3 app/main.py
